swagger: '2.0'

info:
  title: Flask API
  version: '1.0'

consumes:
  - application/json

basePath: /v1

paths:
  /ping:
    get:
      operationId: src.api.endpoints.ping
      responses:
        '200':
          description: OK
